import os

from dotenv import load_dotenv


load_dotenv()

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
OPENAI_MODEL_NAME = os.getenv('OPENAI_MODEL_NAME')
OPENAI_MODEL_TEMPERATURE = os.getenv('OPENAI_MODEL_TEMPERATURE')
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')
GEMINI_MODEL_NAME = os.getenv('GEMINI_MODEL_NAME', 'gemini-2.5-flash')
AI_CONTEXTUALIZE_PROMPT = os.getenv('AI_CONTEXTUALIZE_PROMPT')
AI_SYSTEM_PROMPT = os.getenv('AI_SYSTEM_PROMPT')
VECTOR_STORE_PATH = os.getenv('VECTOR_STORE_PATH')
RAG_FILES_DIR = os.getenv('RAG_FILES_DIR')
EVOLUTION_API_URL = os.getenv('EVOLUTION_API_URL')
EVOLUTION_INSTANCE_NAME = os.getenv('EVOLUTION_INSTANCE_NAME')
EVOLUTION_AUTHENTICATION_API_KEY = os.getenv('AUTHENTICATION_API_KEY')
REDIS_URL = os.getenv('CACHE_REDIS_URI')
BUFFER_KEY_SUFIX = os.getenv('BUFFER_KEY_SUFIX')
DEBOUNCE_SECONDS = os.getenv('DEBOUNCE_SECONDS')
BUFFER_TTL = os.getenv('BUFFER_TTL')

GOOGLE_SHEETS_CREDENTIALS_PATH = os.getenv('GOOGLE_SHEETS_CREDENTIALS_PATH')
GOOGLE_SHEETS_TOKEN_PATH = os.getenv('GOOGLE_SHEETS_TOKEN_PATH')
GOOGLE_SHEETS_SPREADSHEET_ID = os.getenv('GOOGLE_SHEETS_SPREADSHEET_ID')
GOOGLE_SHEETS_CLIENTES_TAB = os.getenv('GOOGLE_SHEETS_CLIENTES_TAB', 'Clientes')
GOOGLE_SHEETS_ESTOQUE_TAB = os.getenv('GOOGLE_SHEETS_ESTOQUE_TAB', 'Estoque')
GOOGLE_SHEETS_PEDIDOS_TAB = os.getenv('GOOGLE_SHEETS_PEDIDOS_TAB', 'Pedidos')
ADMIN_WHATSAPP_NUMBER = os.getenv('ADMIN_WHATSAPP_NUMBER')

# PostgreSQL (SaaS / Supabase)
DATABASE_CONNECTION_URI = os.getenv('DATABASE_CONNECTION_URI')
BOT_DATABASE_CONNECTION_URI = os.getenv('BOT_DATABASE_CONNECTION_URI') or DATABASE_CONNECTION_URI
BOT_ESTOQUE_DEFAULT_CATEGORY = os.getenv('BOT_ESTOQUE_DEFAULT_CATEGORY', 'Sem categoria')
